### ISSUE TITLE
Update Or Remove Example Code

### ISSUE THREAD

**Issue by jamesmcclain** [locationtech-labs/geopyspark#118]
Much of the code the [examples directory](https://github.com/locationtech-labs/geopyspark/tree/bc4d5ec94cfa1af5066abd8cf8f6a260bf0ecf20/examples) seems to no longer work.

**Comment by jbouffard** [comment]
I'm currently in the process of writing new examples https://github.com/jbouffard/geopyspark/blob/perf-docs/docs/ingest_example.rst. So those files will be replaced in the next couple of PRs.

**Comment by jbouffard** [comment]
Resolved in #122
