### ISSUE TITLE
Consider a class-based neighborhood

### ISSUE THREAD

**Issue by moradology** [locationtech-labs/geopyspark#132]
GeoPySpark currently handles focal operations by passing in the type of neighborhood as one parameter and its size as a second (and/or third and/or fourth parameter).

Here's some pseudocode illustrating the strangeness w/r/t arity that we're forced to negotiate with the current strategy:
```python
# Here, the analogy from one piece of syntax to the other is clear
layer.focal(<OPERATION>, Square, <SQUARE_SIZE>)
layer.focal(<OPERATION>, Circle, <CIRCLE_RADIUS>)

# It breaks down, however, when we need more than one specification for neighborhood size
layer.focal(<OPERATION>, Rectangle, <RECT_HEIGHT>, <RECT_WIDTH>)
```
```python
layer.focal(<OPERATION>, Rectangle(<RECT_HEIGHT>, <RECT_WIDTH>))
```
Ideally, I think, we should prefer a single arity for all such operations. This could be handled thusly: `(<OPERATION>, <NEIGHBORHOOD>)`, where <NEIGHBORHOOD> is a class that has whatever arity of constructor makes sense based on the type of neighborhood being constructed

**Comment by echeipesh** [comment]
I like the idea of having class based neighborhoods. It creates classes, which we don't like, but it also clarifies the API and would allow you to pass the focal-hood as a parameter. It also mirrors the way scala API works, which is a plus. @lossyrob ping for 👍 / 👎
