### ISSUE TITLE
Enable python package installation from inside Jupyter

### ISSUE THREAD

**Issue by jpolchlo** [locationtech-labs/geopyspark#137]
It is possible in Jupyter to issue shell commands, including commands to install packages.  Currently, a command such as `!sudo pip install matplotlib` will fail, but it shouldn't.  We should not require a user to `docker exec -u root` into the container to install packages.

Note: one may prefer not to allow global installation though `sudo`, but rather to require `!pip install --user <pkg>`.  These commands might fail due to the absence of certain binary packages (e.g., `pyproj` requires `gcc`).  In this case the user should have permission to at least run `yum install`.

**Comment by jbouffard** [comment]
Would moving to a virtual env for development remedy this issue? As any library you wish to install will have access to packages it needs from your local system.

**Comment by jpolchlo** [comment]
Yes.  That should be adequate.

**Comment by jbouffard** [comment]
Okay. I'll close this issue then.
