### ISSUE TITLE
Explain RasterRDD vs TiledRasterRDD

### ISSUE THREAD

**Issue by echeipesh** [locationtech-labs/geopyspark#148]
There needs to be a visible place that explains the meaning and the purpose of these two classes and how they differ. The python doc strings hint at it but don't provide clear guidance.

Probably a dedicated section in ReadTheDocs is also warranted.

**Comment by jbouffard** [comment]
I did write a brief section on this, but could expand upon it later https://github.com/locationtech-labs/geopyspark/blob/master/docs/core_concepts.rst#how-data-is-stored-in-rdds

**Comment by echeipesh** [comment]
Actually that's perfect, I just didn't look there in haste. I think the python doc string could use a sentence or two vs tiled/untiled and reference to "core concept".

**Comment by jbouffard** [comment]
Okay. I can add that in later today.
