### ISSUE TITLE
TiledRasterRDD.pyramid does not work on layers that are not power of 2

### ISSUE THREAD

**Issue by echeipesh** [locationtech-labs/geopyspark#150]
The `pyramid` function delegates to [`geotrellis.spark.pyramid.Pyramid.levelStream`](https://github.com/locationtech/geotrellis/blob/master/spark/src/main/scala/geotrellis/spark/pyramid/Pyramid.scala#L171) which returns the input RDD as base level.

Therefore if the target `TiledRasterRDD` is not already in power of 2 layout that matches the base zoom level it will be incorrectly returned as the base level and higher level of the pyramid will have malformed output.

Originally there was logic to handle this case that [got removed](https://github.com/locationtech-labs/geopyspark/commit/77487f728b3354cb1944b98509ff601c85e0f13e). Unless there is a better API choice to be made here it should probably be reinstated.

**Comment by jbouffard** [comment]
The reason it was removed was because after I talked with @lossyrob about this, it was decided that it was up to the user to make sure that their inputs are in the correct format. I could add warnings, though, that show up when a bad input is trying to be used.
