### ISSUE TITLE
TMS tile server for Jupyter

### ISSUE THREAD

**Issue by jamesmcclain** [locationtech-labs/geopyspark#18]
At present, we already have the rudiments of a tile server (see #17).  Getting this to a state where it is usable inside of a Jupyter notebook should not be overwhelmingly difficult, but some research into the actual mechanics of how to make it happen might be required.

**Comment by echeipesh** [comment]
Resolved by code in: https://github.com/locationtech-labs/geopyspark/blob/master/docs/sentinel_tile_server_example.rst
