### ISSUE TITLE
Can't install geopyspark in a python virtualenv environment

### ISSUE THREAD

**Issue by rburhum** [locationtech-labs/geopyspark#182]
Repro case:

- Make a [virtualenv](http://cheng.logdown.com/posts/2016/08/12/install-python3-and-virtualenv-on-mac):
```bash
mkvirtualenv --python=/usr/local/bin/python3 spark
```
- add the SPARK_HOME to virtualenv:
`vim ~/.envs/spark/bin/postactivate`
```bash
export SPARK_HOME=/usr/local/spark
```
- Activate virtualenv and install pygeospark
```bash
workon spark
git clone https://github.com/locationtech-labs/geopyspark.git
cd geopyspark
make install
```

You will get the following error message:

I get the following error:
```bash
python3 setup.py install --user --force --prefix=
running install
Checking .pth file support in /Users/rburhum/.local/lib/python3.6/site-packages/
/Users/rburhum/.virtualenvs/spark/bin/python3 -E -c pass
TEST FAILED: /Users/rburhum/.local/lib/python3.6/site-packages/ does NOT support .pth files
error: bad install directory or PYTHONPATH

You are attempting to install a package to a directory that is not
on PYTHONPATH and which Python does not read ".pth" files from.  The
installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

    /Users/rburhum/.local/lib/python3.6/site-packages/

and your PYTHONPATH environment variable currently contains:

    '/Users/rburhum/.virtualenvs/spark/lib/python3.6/site-packages/'

Here are some of your options for correcting the problem:

* You can choose a different installation directory, i.e., one that is
  on PYTHONPATH or supports .pth files

* You can add the installation directory to the PYTHONPATH environment
  variable.  (It must then also be on PYTHONPATH whenever you run
  Python and want to use the package(s) you are installing.)

* You can set up the installation directory to support ".pth" files by
  using one of the approaches described here:

  https://setuptools.readthedocs.io/en/latest/easy_install.html#custom-installation-locations


Please make the appropriate changes for your system and try again.
make: *** [install] Error 1
```

If I edit the Makefile like so:
```bash
rburhum@peru:~/geopyspark$ git diff
diff --git a/Makefile b/Makefile
index 6a884a8..fbc66f3 100644
--- a/Makefile
+++ b/Makefile
@@ -10,7 +10,7 @@ WHEEL := dist/${WHEELNAME}
 rwildcard=$(foreach d,$(wildcard $1*),$(call rwildcard,$d/,$2) $(filter $(subst *,%,$2),$d))

 install: ${DIST-ASSEMBLY} ${WHEEL}
-       ${PYTHON} setup.py install --user --force --prefix=
+       ${PYTHON} setup.py install

 ${DIST-ASSEMBLY}: ${BUILD-ASSEMBLY}
        cp -f ${BUILD-ASSEMBLY} ${DIST-ASSEMBLY}
rburhum@peru:~/geopyspark$
```
and to a `make install` it works fine.

**Comment by jpolchlo** [comment]
The error related to PYTHONPATH can be resolved by ensuring that environment variable is properly set.  Have you tried to `export PYTHONPATH=/Users/rburhum/.virtualenvs/spark/lib/python3.6/site-packages/` inside your virtualenv?  That has worked for me in the past.  Also, take that moment to ensure that your `SPARK_HOME` variable is set and that `$SPARK_HOME/bin` is on your `PATH`.  The path must be set properly if you intend to use the `make pyspark` target.

**Comment by rburhum** [comment]
If you look at:

```bash
/Users/rburhum/.local/lib/python3.6/site-packages/

and your PYTHONPATH environment variable currently contains:

    '/Users/rburhum/.virtualenvs/spark/lib/python3.6/site-packages/'
```
you'll notice that it is doing an output of the $PYTHONPATH contents. If I don't set it, it shows this instead:

```bash
/Users/rburhum/.local/lib/python3.6/site-packages/

and your PYTHONPATH environment variable currently contains:

    ''
```

With either scenario, it doesn't work :( and technically I should not set it since AFAIK that is supposed to be handled by the virtualenv.

$SPARK_HOME is set (the postactivate that I put in the repro instructions sets its) and I can echo it fine. 

IMHO, this issue is related to how setuptools has been configured for python3. Honestly, I have had so many headaches getting setuptools to behave properly with various versions of python that I did not want to go into fixing this black dark hole haha. I believe it is related to setting up the prefix. 

That is why removing those (as in how I modified the Makefile as described) works - the virtualenv takes care of putting the files in the right spot.

**Comment by jpolchlo** [comment]
It may be the case that our installation files assuming a PYTHONPATH of the form `$HOME/.local/lib/<python_version>/site-packages/`, whereas yours does not fit this format.  We'll look into defaulting to the currently set PYTHONPATH during installation.
