### ISSUE TITLE
Unify the API 

### ISSUE THREAD

**Issue by jbouffard** [locationtech-labs/geopyspark#22]
Currently, the two main contributers of GeoPySpark (@jamesmcclain and myself) have been using different naming conventions and implementations in the GeoPySpark API. This has lead to two diverging formats within this library.

For example, the way in which the user interfaces the various GeoPySpark modules is different depending on who wrote the module itself. See [catalog](https://github.com/locationtech-labs/geopyspark/blob/master/geopyspark/geotrellis/catalog.py) and [hadoop_geotiff_rdd](https://github.com/jbouffard/geopyspark/blob/serialization-refactor-2/geopyspark/geotrellis/hadoop_geotiff_rdd.py) scripts which were written by @jamesmcclain and myself, respectively.

In those same scripts, there are also exists different naming conventions; where keys with a time component are referred to as `spacetime` in `catalog` and `temporal` in `hadoop_geotiff_rdd`.

Thus, it would be good to pick either one, or neither, of these two styles and stick with it.

**Comment by jamesmcclain** [comment]
:+1:

**Comment by jbouffard** [comment]
This issue was resolved with PR #29

**Comment by jamesmcclain** [comment]
:tada:
