### ISSUE TITLE
GeoNotebook Layer Handling

### ISSUE THREAD

**Issue by jamesmcclain** [locationtech-labs/geopyspark#223]
This issue would be more appropriately put into the GeoNotebook repository, but I am not able to make issues there.

It seems that layer handling is now behaving strangely.  Typing:
```python
rdd = get(geopysc, SPATIAL, '/tmp/51.tif')
png = PngRDD.makePyramid(rdd.to_tiled_layer(), 'hot')
M.add_layer(RddRasterData(png, 'hotDEM'))
M.add_layer(RddRasterData(png, 'hotDEM'))
M.add_layer(RddRasterData(png, 'hotDEM'))
M.add_layer(RddRasterData(png, 'hotDEM'))
M.add_layer(RddRasterData(png, 'hotDEM'))
M.add_layer(RddRasterData(png, 'hotDEM'))
M.add_layer(RddRasterData(png, 'hotDEM'))
```
then
```python
len(M.layers)
```
will give an answer of `1` instead of `7`.  In spite of this, there will be seven tile servers running.  It is possible to remove the 0th one by typing `M.remove_layer(M.layers[0])`, but there does not seem to be a way to remove the others.

This is true as of `d0d435f6a7f4e61e1f25582453b0139122bf5e6e`.

**Comment by jpolchlo** [comment]
I think the layer adding code replaces layers of with the same name.  That
appears to be the correct behavior if that is the operational semantic.

**Comment by jamesmcclain** [comment]
Well, the behavior in (non-GeoTrellis) GeoNotebooks is for each layer to be a separate layer.

**Comment by jbouffard** [comment]
Should this issue migrate to https://github.com/geotrellis/geonotebook ?

**Comment by jpolchlo** [comment]
Most likely

**Comment by jamesmcclain** [comment]
If someone wouldn't mind giving geotrellis/geonotebook#3 a review, we can close this issue instead of migrating it.

**Comment by jbouffard** [comment]
Resolved in https://github.com/geotrellis/geonotebook/pull/3
