### ISSUE TITLE
Use `mapValues` when possible

### ISSUE THREAD

**Issue by lossyrob** [locationtech-labs/geopyspark#238]
In instances like this: https://github.com/locationtech-labs/geopyspark/blob/7dceb40934e36853c5a1700988388d890748d6fe/geopyspark-backend/geotrellis/src/main/scala/geopyspark/geotrellis/TiledRasterRDD.scala#L176

When you map and don't need to change the key, always use `mapValues`. `map`ping over an RDD gets rid of the partitioner, because the code cannot make any assumptions around what changed about the keys (and the partitioner is based on the keys). With `mapValues`, you keep the partitioner around.

**Comment by jbouffard** [comment]
Just put #239 that resolves with issue.
