### ISSUE TITLE
Configure SparkConf outside of kernel.json

### ISSUE THREAD

**Issue by echeipesh** [locationtech-labs/geopyspark#285]
We should be able to configure SparkConf for local or yarn in the notebook.
- Add jars
~~- Add python modules_~~
- Add native dependencies.

**Comment by jpolchlo** [comment]
If PR #304 is acceptable, it handles the pathway for adding JARs.  Native dependencies are best dealt with by setting up the environment properly.  In the local case, this is ensuring that the native libraries are on the LD_LIBRARY_PATH, and in the YARN case, that the `--archives` option in the docker kernel are set properly.  We might consider dispensing with the idea that we can do this for all users in a nice automatic fashion.

No immediate bright ideas on the adding of python modules.

**Comment by echeipesh** [comment]
Shipping python modules can/should be broken out into its own issue. 304 looks well scoped for this.

**Comment by echeipesh** [comment]
Resolved by: https://github.com/locationtech-labs/geopyspark/pull/304
