### ISSUE TITLE
Use `Neighborhood` class in `def focal`

### ISSUE THREAD

**Issue by echeipesh** [locationtech-labs/geopyspark#297]
[Neighbohood](https://github.com/locationtech-labs/geopyspark/blob/master/geopyspark/geotrellis/neighborhood.py) was written but the focal operation still uses the `name, param1, param2` format. Should be updated to use the class.

**Comment by jbouffard** [comment]
Those parameters were kept in so that the user doesn't have to define an instance of `Neighborhood` and instead could use a constant or string.

**Comment by jbouffard** [comment]
This issue was opened due to a misunderstanding that has since been resolved. Thus, I'm closing it.
