### ISSUE TITLE
Work With Specific Bands of a MultibandTile

### ISSUE THREAD

**Issue by jbouffard** [locationtech-labs/geopyspark#324]
Right now, operations, analysis, and display are performed on all bands. However, as @rossbernet pointed out, there are times when the focus is just on a few bands, and not all of them. Therefore, it would be beneficial if we had some API to address this before releasing 0.2.

Here are a few possible implementations of this API:

- Have the option available when reading

```python
  # Only the first and third band will be read in from the files

  raster_layer = get(pysc, "Spatial", "/path/to/my/files", bands_of_interest=[0, 2])
  tiled_layer = query(pysc, "Spatial", "file://path/to/my/catalog", "test-layer", 10, bands_of_interest=[0, 2])
```

- A special filter method on the layers

```python
  # Only the first band will taken

  filtered_raster_layer = raster_layer.select_bands(0)
  filtered_tiled_layer = tiled_layer.select_bands(0)
```

- Selecting bands during operations

```python
  # Polygonal min on only the second and third bands

  polygonal_min = tiled_layer.polygonal_min(my_geom, int, bands_of_interest=[1, 2])
```

Of the above three, I like the first two the most. The latter would require too much rewriting of existing methods/function, in my opinion. @echeipesh @jpolchlo What do you guys think?

**Comment by rossbernet** [comment]
This came out of the recognition that I would like to perform an NDVI on a multiband geotiff.

For example - how would I perform an NDVI on a Landsat?

[This is](https://developers.google.com/earth-engine/tutorial_api_06) how google earth engine does it 

There may be a time when you only are interested in loading a subset of bands - perhaps for performance cosiderations.

But I would like to be able to ingest a geotiff as normal, and then later be able to do:

landsatRDD.band1 + landsatRdd.band2 / landsatRdd.band1 - landsatRDD.band2

^^ that is probably not the right syntax. But I hope it captures the flavor of being able to easily specify a band and operate on it like that.

**Comment by jbouffard** [comment]
To get something like that, we'd have to implement something like this on the Python side:

```python
def _get_bands(self):
  c = 1
  
  while True:
    try:
      srdd_subset = self.srdd.get_band(c - 1)
      layer_subset = TiledRasterLayer(self.pysc, self.rdd_type, srdd_subset)
      attribute_name '_'.join(['band', str(c)])
      
      setattr(self, attribute_name, layer_subset)
      
      c += 1
      
    except:
      break
      pass
```

What's happening in this method is that new layer instances will be created for each band within the `MultibandTile`. It will keep looping until an error is thrown from Scala saying that the band being requested is out of bounds. This will be ignored, and since the error signals the end of the bands, the loop will be stopped. Each new attribute will be in the form of `band_n` where `n` is the band number.

There are a few things I don't like about this, though. The first being there is now additional overhead when initializing a new instance of one of the layer classes; and creation is quite frequent. My other issue is the lack of consistency between instances that this would create. For example, right now we know exactly what attributes an instance of `TiledRasterLayer` has when it's first created. However, we will not be able to know for sure (at least at time of creation) with this implementation.

Both of the above could mitigated by having additional attributes like, `band_count` and `bands`. Where the first is total number of bands within the layer and the latter being a list of all the subsections. 

What could work as an alternative instead, is something similar to what I had suggested:

```python
band_1 = landsatRDD.select_bands(0)
band_2 = landsatRDD.select_bands(1)

band_1 + band_2 / band_1 - band_2
```

**Comment by echeipesh** [comment]
We want the layer unpacking as above. It would be good if it supported array slice syntax.

But to avoid the joins that it generates we should have a way to work on raw numpy values like:

```py
def numpy_ndvi(cells,nd_value): 
    return (cells[3] - cells[2]) / (cells[3] + cells[2])

# RasterLayer / TiledRasterLayer
lake.numpy_map_cells(numpy_ndvi)

# Or Lambda
lake.numpy_map_cells(
    lambda (cells, nd): (cells[3]-cells[2])/(cells[3]+cells[2])
)
```

Chaining option
```py
py_like.mapValues(
    lambda tile: tile.map_cells(
        lambda band: (band[3]-band[2])/(band[3]+band[2])
    )
).mapValues(
    lambda tile: tile.map_cells(
        lambda band: band[0] + 100
    )
)
```
