### ISSUE TITLE
Change println to logger usage

### ISSUE THREAD

**Issue by echeipesh** [locationtech-labs/geopyspark#346]
There are several places where debug printing is happening at the moment. For the release we should change them to logger usage and have a little blurb in the docs how to configure the logging for debugging to make sure that it can be enable and useful in the future.

**Comment by jpolchlo** [comment]
@jamesmcclain : Is this taken care of by #364 ?

**Comment by jamesmcclain** [comment]
`grep --include='*.scala' -r 'println' .` returns no results for me on master...
