### ISSUE TITLE
Check for SparkContext Initialization

### ISSUE THREAD

**Issue by jbouffard** [locationtech-labs/geopyspark#368]
Right now, we force the user to pass around an instance of `SparkContext`. Instead, we should check to make sure it was set globally.

**Comment by jbouffard** [comment]
After working on this for a bit, I'm realizing it might be better to make the `SparkContext` parameter optional rather than removing it entirely. My reasoning for this is because we will be making a lot of unneeded calls to get the `SparkContext` if we are unable to pass it around. For example, each new instance of a `Layer` class will need to find the current `SparkContext` since it's required to perform almost all of the methods in that class. However, this seems wasteful as the previous instance already has the `SparkContext` as an attribute.

I think the following would work better:

```python

def __init__(self, layer_type, srdd, pysc=None):
    self.pysc = pysc or get_spark_context()
```

**Comment by echeipesh** [comment]
That makes sense and is a nice escape hatch if ever there is two contexts

**Comment by jpolchlo** [comment]
Seems like a fine thing to do.  +1
