### ISSUE TITLE
Sample workbooks to include in .2 release

### ISSUE THREAD

**Issue by rossbernet** [locationtech-labs/geopyspark#383]
We should include sample geonotebook demos with the .2 release that are accessible either through the geodocker repo or directly in the GPS repo - following the example of [geonotebook](https://github.com/OpenGeoscience/geonotebook/tree/master/notebooks)

1. simple local / focal operations via the elevation tree siting demo

2. Euclidean distance raster generation - potentially from the Bay Area example? Or something like it.

3. Libya MVP (and/or something else showing cost distance)

4. NLCD clipping values - Chatta

5. Something that shows doing something to satellite imagery from AWS. @jpolchlo made this [gist](https://gist.github.com/jpolchlo/bbcc764687127df83b34dce348418a54) Perhaps we could extend it and do an NDVI on it. And if we wanted to get fancy, show a change detection NDVI comparing NDVI for two dates particularly where we know something changed to make a point. 

Any other functionality we should demonstrate? And comments?

**Comment by jbouffard** [comment]
These sample workbooks were added to the https://github.com/geodocker/geodocker-jupyter-geopyspark repo in this PR https://github.com/geodocker/geodocker-jupyter-geopyspark/pull/48
