### ISSUE TITLE
Home for reproject to layout functionality

### ISSUE THREAD

**Issue by echeipesh** [locationtech-labs/geopyspark#394]
There exist a functionality in GeoTrellis that performs a "buffered" reproject, as if reproject was a focal operation, this version of reproject does not produce any tile seams and always produces a tiled layer as a result.

Pretty much by definition it is a combination of raster tiling and raster reproject operations, so the question is where does it belong most naturally:

## Home in Reproject

We can treat it as having a home in `reproject` function:
```py
tiffs = geotiff.get("s3://bucket/geotiffs/")

# perform per-tile reproject, result: RasterLayer
tiffs.reproject("espg:3857")

# perform buffered reproject result: TiledRasterLayer
tiffs.reproject("epsg:3857", layout = GlobalLayout(tile_size=256))
```

Here we specified `layout` argument, which defaults to `None` to invoke the functionality.

## Home in `tile_to_layout`
`tile_to_layout` is function concerned with changing the way the layer is tiled, see discussion here https://github.com/locationtech-labs/geopyspark/issues/369

Currently it will throw if it realized that any of the argument specifies a different CRS from the source layer, but we could change that ...

```py
# change the layout to one that covers the world extent, result: TiledRasterLayer
tiled_layer.tile_to_layout(layout=GlobalLayout())

# insert a reprojection step into the tiling process, changing the CRS
tiled_layer.tile_to_layout(layout=GlobalLayout(crs="epsg:3857"))

# another way to do the same thing, maybe this is more discoverable?
tiled_layer.tile_to_layout(layout=GlobalLayout(), crs="epsg:3857")

# What about reproject on tiled layer?
# I guess we have to try to preserve the layout type, implicitly preserving either LocalLayout or GlobalLayout
tiled_layer.reproject("epsg:3857") 
```

## The Crux

Either `tile_to_layout` or `reproject` has to provide a home for the combination of the two. Choosing one seems to render the other feeling somewhat inconsistent.

**Comment by jbouffard** [comment]
Resolved in #379
