### ISSUE TITLE
NLCD workbook

### ISSUE THREAD

**Issue by lossyrob** [locationtech-labs/geopyspark#413]
This issue is to write a well-documented GeoPySpark/GeoNoteBook notebook that does the following:

- Loads up an NLCD layer (tms layer, `nlcd-zoomed`) and paints it on the map
- Queries by a state (take https://raw.githubusercontent.com/johan/world.geo.json/master/countries/USA/FL.geo.json), masks by the polygon, paints that on the map
- Reclass developed area (21-24) to 1 and forest (41-43) to 2, everything else to NODATA. Paint that on the map with a custom color ramp.
- Compute a count of each class over the state.

**Comment by jbouffard** [comment]
https://github.com/geodocker/geodocker-jupyter-geopyspark/pull/48
