### ISSUE TITLE
Landsat 8 workbook

### ISSUE THREAD

**Issue by lossyrob** [locationtech-labs/geopyspark#414]
Write a well documented workbook that does the following:

- Queries a landsat 8 geotrellis pyramided layer for a state (https://raw.githubusercontent.com/johan/world.geo.json/master/countries/USA/FL.geo.json), and reads it as a spatiotemporal layer
- Inspects what dates the layer has
- Move from a spatiotemporal layer to a spatial layer for one of the dates
- Render that scene onto the GeoNotebook map
- Color correct that scene (can use magic numbers and other code from: https://github.com/geotrellis/geotrellis-landsat-emr-demo/blob/master/server/src/main/scala/demo/Render.scala#L24
- Compute NDVI on that scene, paint it on the map
- Draw a polygon with GeoNotebook, and grab that shapely shape
- Use that as the basis to do the spatiotemporal polygonal summary, to get a time series data set of the NDVI over that area per scene period (on the original statewide spatiotemporal layer)

**Comment by jbouffard** [comment]
https://github.com/geodocker/geodocker-jupyter-geopyspark/pull/48
