### ISSUE TITLE
NDVI/CDL workbook

### ISSUE THREAD

**Issue by lossyrob** [locationtech-labs/geopyspark#415]
Using the spatiotemporal layer from https://github.com/locationtech-labs/geopyspark/issues/414, write a workbook that:

- Combines the state-level spatiotemporal NDVI layer and the spatial CDL crop layer to produce a masked version of the NDVI that is the NDVI value when the pixel is over a specific crop value, and NoData everywhere else
- Do the timeseries polygonal summary of NDVI over the state.
- This is an indicator for that crop type's health over the period of 2016. From this we should be able to derive the growing season in 2016 for that crop.

**Comment by jbouffard** [comment]
Resolved in https://github.com/geodocker/geodocker-jupyter-geopyspark/pull/48
