### ISSUE TITLE
get_histogram needs to return StreamingHistogram by default, exact histogram optionally

### ISSUE THREAD

**Issue by lossyrob** [locationtech-labs/geopyspark#439]
https://github.com/locationtech-labs/geopyspark/blob/c4fe47c680b97fea7d250fcbe2bc985b8e81256c/geopyspark/geotrellis/layer.py#L1387

The reason we differentiate between Streaming and Int histograms is more than the data type. A Histrogram[Int] (underlying value is `FastMapHistogram`) gives exact value to counts for the buckets; internally it keeps an exact count of every time it has seen each value. If you have a plethora of values (e.g. in a Landsat image), you'll be holding on to a whole lot of data in that histogram.

The Streaming histogram, on the other hand, contains some discrete set of buckets that has a max limit to the number of buckets. Each new value it sees changes the bucket centers, which are not exact values but approximations of the values that bucket represents. This allows us to compute histogram over very large data, since it will always only hold the maximum number of buckets.

Because RDDs tend to be large, by default we should do the thing which won't fail, which is the Streaming histogram. If the user wants an exact integer histogram, they should ask for it specifically. This is where the `histogram` vs `histogramExactInt` API comes from in GeoTrellis.

**Comment by lossyrob** [comment]
It looks like `get_quantile_breaks` has an exactInt type method; we should work out how these relate

**Comment by jbouffard** [comment]
This issue was resolved in #455
