### ISSUE TITLE
rasterizer bug 

### ISSUE THREAD

**Issue by rossbernet** [locationtech-labs/geopyspark#510]
When replicating the san fran mvp at a state wide level with a higher zoom level the poly line rasterizer gives some blocky results:

This PR in geotrellis fixes it: https://github.com/locationtech/geotrellis/pull/2336
But it hasnt made its way into geopyspark yet.

![image](https://user-images.githubusercontent.com/8103418/31028692-df989056-a51c-11e7-9d80-fa5574a2184a.png)

**Comment by echeipesh** [comment]
This issue has been addressed and is part of the rasterized used in GeoTrellis.
