### ISSUE TITLE
Out-of-date Examples

### ISSUE THREAD

**Issue by xinranduan** [locationtech-labs/geopyspark#543]
Hello,

I found that the quick example in readme seems to be still using old API that is not supported by the latest release anymore.

To create a Spark Conf, it should be

conf = gps.**geopyspark_conf**(master="local[*]", appName="ingest-example")

instead of
conf = gps.**create_geopyspark_conf**(...)

**Comment by jbouffard** [comment]
Hello, @xinranduan! Thanks for pointing out this issue. We created another issue a few days ago that describes this problem #534. Though, that one was a bit more general.

If you ever run into any other problems, please feel free to contact us on [gitter](https://gitter.im/geotrellis/geotrellis) or the mailing list.

**Comment by jbouffard** [comment]
@xinranduan just wanted to let you know that there is now a PR up that resolves this issue #553

**Comment by jbouffard** [comment]
@xinranduan This issue has been resolved by #553
