### ISSUE TITLE
KeyError: 'y'     # Create the SparkContext 

### ISSUE THREAD

**Issue by hll1213181368** [locationtech-labs/geopyspark#578]
when I Create the SparkContext used the underline codes

# Create the SparkContext
conf = gps.geopyspark_conf(appName="geopyspark-example", master="local[*]")
sc = SparkContext(conf=conf)

in the py4j-0.9-src.zip/py4j/java_gateway.py. The function java_import:
answer = gateway_client.send_command(command)   -----> Return "answer='!yv'"

so throws the KeyError:'y'

Anyone can help me! Thanks!

**Comment by hll1213181368** [comment]
![_20171210135852](https://user-images.githubusercontent.com/17724484/33802440-4d351c9c-ddb2-11e7-896c-02ec379a0476.png)

**Comment by hll1213181368** [comment]
![2017-12-10 23-22-50](https://user-images.githubusercontent.com/17724484/33806321-88283b0a-de01-11e7-9587-cd618de6d7ed.png)


@jnh5y @echeipesh @lossyrob @yoninachmany @eclipsewebmaster    Can you help me! Thanks~

**Comment by jamesmcclain** [comment]
@jbouffard

**Comment by jbouffard** [comment]
Hello, @hll1213181368. Assuming that the `SPARK_HOME,` `SPARK_CLASSPATH`, and `master` are correct, then this issue appears to be due to something with Spark/Hadoop. As mentioned by @jpolchlo in #579, updating the Spark/Hadoop versions could possibly resolve your issue.

I will also try running GPS with your versions of Spark/Hadoop to confirm  whether or not that is the issue.

**Comment by jbouffard** [comment]
@hll1213181368 I was able to confirm that Spark 1.6.0 and Hadoop 2.6 are not compatible with the latest version of GeoPySpark. Sorry that the docs were not correct, I'll update them now.

**Comment by hll1213181368** [comment]
@jbouffard  OK! Thank you very much！

**Comment by jbouffard** [comment]
@hll1213181368 You're welcome! Please let us know if that works for you.

**Comment by hll1213181368** [comment]
@jbouffard I have solved this problem when I change the version of Hadoop and Spark. Thank you very much!

**Comment by jbouffard** [comment]
@hll1213181368 You're welcome! I'm glad we were able to resolve your issue!
