### ISSUE TITLE
Dana Tomlin Demo of Python Bindings for GeoTrellis 

### ISSUE THREAD

**Issue by rossbernet** [locationtech-labs/geopyspark#58]
Moving over this issue from: https://github.com/locationtech/geotrellis/issues/1987#issuecomment-285915182

Is there a better method of doing it than copy pasting comment history? 

---

rossbernet commented on Jan 26
Dana Tomlin has expressed interest in using GeoTrellis in his software design course at Penn and Yale.

To do this, we need to work with him first to understand his needs / hopes / expectations for how this could be used in class.

We plan for this to involve python bindings, a jupyter notebook, and the ability to use primitive map algebraic methods. With a straight forward way of accessing raster data sets.
 @rossbernet rossbernet added the python bindings label on Jan 26
 @rossbernet rossbernet added this to the 1.1 milestone on Jan 26
 @rossbernet rossbernet self-assigned this on Jan 26
 @rossbernet rossbernet added to TODO in 1.1 - April on Jan 26
@kotfic
     
kotfic commented on Jan 26
Just as an FYI, we're actively working on integrating Geotrellis into an open source extension to the Jupyter notebook OpenGeoscience/geonotebook. The software is still under active development, but there may be an opportunity for collaboration
 @jpolchlo
     Contributor
 jpolchlo commented on Jan 26 • edited
I don't know exactly what your plans are, but you may want to check out geodocker/geodocker-geotrellis-jupyter where we have a docker container that uses Apache Toree to give you access to a Scala notebook with a SparkContext and Geotrellis.  Your project is clearly of a more complex nature, but that container may provide you some utility.

I should also note that we are working on Python bindings to Geotrellis (locationtech-labs/GeoPySpark repo).  I'm working on extensions to the earlier Docker container to provide access to those facilities.
 @dorukozturk
     
dorukozturk commented on Jan 26
Those look very interesting. We will definitely look into them more closely.
 @lossyrob
     Member
lossyrob commented on Jan 26
@kotfic this looks like a great project. If there's any help we can give with the extension, let us know. It would be great to find a way to collaborate! We'll be taking a deeper look into the project soon.
 @lossyrob lossyrob modified the milestone: 1.2, 1.1 2 days ago
@lossyrob
     Member
lossyrob commented 2 days ago
This has to do with projects that were moved outside of core GeoTrellis - should we make issues there and track in a different place? /cc @rossbernet

**Comment by jbouffard** [comment]
This has been resolved.
