### ISSUE TITLE
How to get the values of different bands for tiff images? 

### ISSUE THREAD

**Issue by hll1213181368** [locationtech-labs/geopyspark#594]

**Comment by hll1213181368** [comment]
OK! I have solved this problem~

**Comment by jbouffard** [comment]
@hll1213181368 I'm glad you were able to solve the problem! If you have questions similar to this one in the future, please let us know on our [Gitter channel](https://gitter.im/geotrellis/geotrellis). We'd like to have Github issues be more on bugs/features.
