### ISSUE TITLE
Regression in geopyspark install

### ISSUE THREAD

**Issue by jdries** [locationtech-labs/geopyspark#624]
I  have  a build failure due to an attempt to
from geopyspark.geopyspark_constants import JAR, CWD
in configuration.py
While geopyspark_constants only contains GEOTRELLIS_JAR.
Build link:
https://travis-ci.org/Open-EO/openeo-geopyspark-driver/jobs/332778493

**Comment by jbouffard** [comment]
@jdries Thank you so much for bringing another error to our attention! This regression was caused by left over code that should have cleaned up. I put up #625 that will resolve this issue.
