### ISSUE TITLE
Example in Readme.rst not runnable

### ISSUE THREAD

**Issue by markwestcott34** [locationtech-labs/geopyspark#633]
https://s3-us-west-2.amazonaws.com/prd-tnm/StagedProducts/NLCD/2011/landcover/states/NLCD2011_LC_Pennsylvania.zip?ORIG=513_SBDDG

is no longer valid. I haven't been able to find an alternative source (although NLCD for the Contiguous USA is available from http://www.landfire.gov/bulk/downloadfile.php?TYPE=nlcd2011&FNAME=nlcd_2011_landcover_2011_edition_2014_10_10.zip)

**Comment by jbouffard** [comment]
Thank you for bringing this to our attention! I'll need to try and find another source since that's not our S3 bucket. In the meantime, I believe that the example should still work with the `tiff` that you found (though it may run a bit slower).

**Comment by jbouffard** [comment]
This issue was resolved in #648
